title: Russell Tsuchida
author: Russell Tsuchida
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about machine learning.

# social links
twitter_username: RussellTsuchida # DO NOT include the @ character, or else the build will fail!
github_username:  RussellTsuchida # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
